buildscript {
    ext.compileSdkVersion = 34
    ext.minSdkVersion = 23
    ext.targetSdkVersion = 34
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    if (project.name != "app") {
        project.ext.flutter = [
            compileSdkVersion: 34,
            minSdkVersion: 23,
            targetSdkVersion: 34,
            ndkVersion: "25.1.8937393"
        ]
    }

    plugins.withId('com.android.library') {
        android {
            namespace = "com.bhai.bhai_app.${project.name}"
        }

        project.tasks.matching { it.name.startsWith("process") && it.name.endsWith("Manifest") }.configureEach { task ->
            task.doFirst {
                def manifestFile = project.file("src/main/AndroidManifest.xml")
                if (manifestFile.exists()) {
                    def content = manifestFile.text
                    if (content.contains('package=')) {
                        content = content.replaceAll(/package="[^"]*"/, "")
                        manifestFile.text = content
                    }
                }
            }
        }
    }
    plugins.withId('com.android.application') {
        android {
            namespace = "com.bhai.bhai_app.${project.name}"
        }
    }

    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
