import 'package:flutter/material.dart';

class AppLocalizations {
  final String language;

  AppLocalizations(this.language);

  static const List<String> supportedLanguages = [
    'English', 'Hindi', 'Telugu', 'Tamil', 'Kannada', 
    'Malayalam', 'Marathi', 'Gujarati', 'Punjabi', 'Bengali', 'Odia'
  ];

  static final Map<String, Map<String, String>> _localizedValues = {
    'English': {
      'tagline': 'Your Brother is Always With You',
      'sos_btn': 'SOS',
      'sos_desc': 'PRESS IN EMERGENCY',
      'safe_status': 'You are Safe',
      'unsafe_status': 'Emergency Active',
      'volunteer_mode': 'Volunteer Mode',
      'volunteer_desc': 'Be available to help nearby victims',
      'home': 'Home',
      'contacts': 'Contacts',
      'helplines': 'Helplines',
      'settings': 'Settings',
      'fake_call': 'Fake Call',
      'travel_mode': 'Travel Mode',
      'safe_places': 'Safe Places',
      'permissions': 'Permissions Screen',
      'permission_desc': 'We need access to ensure your security.',
      'location_perm': 'Location Permission',
      'camera_perm': 'Camera Permission',
      'mic_perm': 'Microphone Permission',
      'sms_perm': 'SMS Permission',
      'notification_perm': 'Notification Permission',
      'next': 'Next',
      'get_started': 'Get Started',
      'save': 'Save',
      'cancel': 'Cancel',
    },
    'Hindi': {
      'tagline': 'आपका भाई हमेशा आपके साथ है',
      'sos_btn': 'आपातकालीन',
      'sos_desc': 'आपातकाल में दबाएं',
      'safe_status': 'आप सुरक्षित हैं',
      'unsafe_status': 'आपातकाल सक्रिय',
      'volunteer_mode': 'स्वयंसेवक मोड',
      'volunteer_desc': 'आसपास के पीड़ितों की मदद के लिए उपलब्ध रहें',
      'home': 'मुख्य पृष्ठ',
      'contacts': 'संपर्क',
      'helplines': 'हेल्पलाइन',
      'settings': 'सेटिंग्स',
      'fake_call': 'नकली कॉल',
      'travel_mode': 'यात्रा मोड',
      'safe_places': 'सुरक्षित स्थान',
      'permissions': 'अनुमतियाँ',
      'permission_desc': 'सुरक्षा सुनिश्चित करने के लिए अनुमति आवश्यक है।',
      'location_perm': 'स्थान की अनुमति',
      'camera_perm': 'कैमरा अनुमति',
      'mic_perm': 'माइक्रोफोन अनुमति',
      'sms_perm': 'एसएमएस अनुमति',
      'notification_perm': 'अधिसूचना अनुमति',
      'next': 'आगे बढ़ें',
      'get_started': 'शुरू करें',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
    },
    'Telugu': {
      'tagline': 'మీ సోదరుడు ఎల్లప్పుడూ మీతో ఉంటాడు',
      'sos_btn': 'ఆపద',
      'sos_desc': 'అత్యవసర సమయంలో నొక్కండి',
      'safe_status': 'మీరు సురక్షితంగా ఉన్నారు',
      'unsafe_status': 'అత్యవసర పరిస్థితి సక్రియంగా ఉంది',
      'volunteer_mode': 'వాలంటీర్ మోడ్',
      'volunteer_desc': 'సమీపంలోని బాధితులకు సహాయం చేయడానికి సిద్ధంగా ఉండండి',
      'home': 'హోమ్',
      'contacts': 'పరిచయాలు',
      'helplines': 'హెల్ప్‌లైన్లు',
      'settings': 'సెట్టింగులు',
      'fake_call': 'ఫేక్ కాల్',
      'travel_mode': 'ట్రావెల్ మోడ్',
      'safe_places': 'సురక్షిత ప్రదేశాలు',
      'permissions': 'అనుమతులు',
      'permission_desc': 'మీ భద్రతను నిర్ధారించడానికి మాకు అనుమతులు అవసరం.',
      'location_perm': 'స్థాన అనుమతి',
      'camera_perm': 'కెమెరా అనుమతి',
      'mic_perm': 'మైక్రోఫోన్ అనుమతి',
      'sms_perm': 'SMS అనుమతి',
      'notification_perm': 'నోటిఫికేషన్ అనుమతి',
      'next': 'తరువాత',
      'get_started': 'ప్రారంభించండి',
      'save': 'సేవ్',
      'cancel': 'రద్దు చేయి',
    },
    'Tamil': {
      'tagline': 'உங்கள் சகோதரன் எப்போதும் உங்களுடன் இருக்கிறான்',
      'sos_btn': 'உதவி',
      'sos_desc': 'அவசரகாலத்தில் அழுத்தவும்',
      'safe_status': 'நீங்கள் பாதுகாப்பாக இருக்கிறீர்கள்',
      'unsafe_status': 'அவசரநிலை செயலில் உள்ளது',
      'volunteer_mode': 'தன்னார்வலர் பயன்முறை',
      'volunteer_desc': 'அருகிலுள்ள பாதிக்கப்பட்டவர்களுக்கு உதவ தயாராக இருங்கள்',
      'home': 'முகப்பு',
      'contacts': 'தொடர்புகள்',
      'helplines': 'உதவி எண்கள்',
      'settings': 'அமைப்புகள்',
      'fake_call': 'போலி அழைப்பு',
      'travel_mode': 'பயண முறை',
      'safe_places': 'பாதுகாப்பான இடங்கள்',
      'permissions': 'அனுமதிகள்',
      'permission_desc': 'உங்களுக்கு பாதுகாப்பு வழங்க அனுமதிகள் தேவை.',
      'location_perm': 'இருப்பிட அனுமதி',
      'camera_perm': 'கேமரா அனுமதி',
      'mic_perm': 'ஒலிவாங்கி அனுமதி',
      'sms_perm': 'SMS அனுமதி',
      'notification_perm': 'அறிவிப்பு அனுமதி',
      'next': 'அடுத்து',
      'get_started': 'தொடங்குங்கள்',
      'save': 'சேமி',
      'cancel': 'ரத்துசெய்',
    },
    'Kannada': {
      'tagline': 'ನಿಮ್ಮ ಸಹೋದರ ಯಾವಾಗಲೂ ನಿಮ್ಮೊಂದಿಗಿರುತ್ತಾನೆ',
      'sos_btn': 'ಸಹಾಯ',
      'sos_desc': 'ತುರ್ತು ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ ಒತ್ತಿರಿ',
      'safe_status': 'ನೀವು ಸುರಕ್ಷಿತವಾಗಿದ್ದೀರಿ',
      'unsafe_status': 'ತುರ್ತು ಪರಿಸ್ಥಿತಿ ಸಕ್ರಿಯವಾಗಿದೆ',
      'volunteer_mode': 'ಸ್ವಯಂಸೇವಕ ಮೋಡ್',
      'volunteer_desc': 'ಹತ್ತಿರದ ಸಂತ್ರಸ್ತರಿಗೆ ಸಹಾಯ ಮಾಡಲು ಲಭ್ಯವಿರಿ',
      'home': 'ಮುಖಪುಟ',
      'contacts': 'ಸಂಪರ್ಕಗಳು',
      'helplines': 'ಹೆಲ್ಪ್ ಲೈನ್ ಗಳು',
      'settings': 'ಸಂಯೋಜನೆಗಳು',
      'fake_call': 'ನಕಲಿ ಕರೆ',
      'travel_mode': 'ಪ್ರಯಾಣ ಮೋಡ್',
      'safe_places': 'ಸುರಕ್ಷಿತ ಸ್ಥಳಗಳು',
      'permissions': 'ಅನುಮತಿಗಳು',
      'permission_desc': 'ನಿಮ್ಮ ಭದ್ರತೆಯನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ಅನುಮತಿ ಅಗತ್ಯವಿದೆ.',
      'location_perm': 'ಸ್ಥಳದ ಅನುಮತಿ',
      'camera_perm': 'ಕ್ಯಾಮೆರಾ ಅನುಮತಿ',
      'mic_perm': 'ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ',
      'sms_perm': 'SMS ಅನುಮತಿ',
      'notification_perm': 'ಅಧಿಸೂಚನೆ ಅನುಮತಿ',
      'next': 'ಮುಂದೆ',
      'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
      'save': 'ಉಳಿಸು',
      'cancel': 'ರದ್ದುಗೊಳಿಸು',
    },
    'Malayalam': {
      'tagline': 'നിങ്ങളുടെ സഹോദരൻ എപ്പോഴും നിങ്ങളോടൊപ്പമുണ്ട്',
      'sos_btn': 'സഹായം',
      'sos_desc': 'അടിയന്തിര ഘട്ടങ്ങളിൽ അമർത്തുക',
      'safe_status': 'നിങ്ങൾ സുരക്ഷിതനാണ്',
      'unsafe_status': 'അടിയന്തരാവസ്ഥ സജീവമാണ്',
      'volunteer_mode': 'വളണ്ടിയർ മോഡ്',
      'volunteer_desc': 'അടുത്തുള്ള ഇരകളെ സഹായിക്കാൻ സന്നദ്ധരാവുക',
      'home': 'ഹോം',
      'contacts': 'കോൺടാക്റ്റുകൾ',
      'helplines': 'ഹെൽപ്പ് ലൈനുകൾ',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'fake_call': 'വ്യാജ കോൾ',
      'travel_mode': 'യാത്രാ മോഡ്',
      'safe_places': 'സുരക്ഷിത സ്ഥലങ്ങൾ',
      'permissions': 'അനുമതികൾ',
      'permission_desc': 'സുരക്ഷിതത്വം ഉറപ്പാക്കാൻ അനുമതികൾ ആവശ്യമാണ്.',
      'location_perm': 'ലൊക്കേഷൻ അനുമതി',
      'camera_perm': 'ക്യാമറ അനുമതി',
      'mic_perm': 'മൈക്രോഫോൺ അനുമതി',
      'sms_perm': 'എസ്എംഎസ് അനുമതി',
      'notification_perm': 'നോട്ടിഫിക്കേഷൻ അനുമതി',
      'next': 'അടുത്തത്',
      'get_started': 'ആരംഭിക്കുക',
      'save': 'സൂക്ഷിക്കുക',
      'cancel': 'റദ്ദാക്കുക',
    },
    'Marathi': {
      'tagline': 'तुमचा भाऊ नेहमी तुमच्या पाठीशी आहे',
      'sos_btn': 'मदत',
      'sos_desc': 'आणीबाणीत दाबा',
      'safe_status': 'तुम्ही सुरक्षित आहात',
      'unsafe_status': 'आणीबाणी सुरू आहे',
      'volunteer_mode': 'स्वयंसेवक मोड',
      'volunteer_desc': 'जवळपासच्या पीडितांना मदत करण्यासाठी उपलब्ध व्हा',
      'home': 'मुख्यपृष्ठ',
      'contacts': 'संपर्क',
      'helplines': 'हेल्पलाइन',
      'settings': 'सेटिंग्ज',
      'fake_call': 'फेक कॉल',
      'travel_mode': 'प्रवास मोड',
      'safe_places': 'सुरक्षित जागा',
      'permissions': 'परवानग्या',
      'permission_desc': 'सुरक्षितता राखण्यासाठी परवानग्या आवश्यक आहेत.',
      'location_perm': 'स्थानाची परवानगी',
      'camera_perm': 'कॅमेरा परवानगी',
      'mic_perm': 'मायक्रोफोन परवानगी',
      'sms_perm': 'एसएमएस परवानगी',
      'notification_perm': 'सूचना परवानगी',
      'next': 'पुढे',
      'get_started': 'सुरू करा',
      'save': 'जतन करा',
      'cancel': 'रद्द करा',
    },
    'Gujarati': {
      'tagline': 'તમારો ભાઈ હંમેશા તમારી સાથે છે',
      'sos_btn': 'મદદ',
      'sos_desc': 'કટોકટીમાં દબાવો',
      'safe_status': 'તમે સુરક્ષિત છો',
      'unsafe_status': 'કટોકટી સક્રિય છે',
      'volunteer_mode': 'સ્વયંસેવક મોડ',
      'volunteer_desc': 'આસપાસના પીડિતોને મદદ કરવા માટે ઉપલબ્ધ રહો',
      'home': 'હોમ',
      'contacts': 'સંપર્કો',
      'helplines': 'હેલ્પલાઇન',
      'settings': 'સેટિંગ્સ',
      'fake_call': 'ફેક કોલ',
      'travel_mode': 'યાત્રા મોડ',
      'safe_places': 'સુરક્ષિત સ્થાનો',
      'permissions': 'પરવાનગીઓ',
      'permission_desc': 'તમારી સુરક્ષા સુનિશ્ચિત કરવા માટે પરવાનગીઓ જોઈએ.',
      'location_perm': 'લોકેશન પરવાનગી',
      'camera_perm': 'કેમેરા પરવાનગી',
      'mic_perm': 'માઇક્રોફોન પરવાનગી',
      'sms_perm': 'SMS પરવાનગી',
      'notification_perm': 'નોટિફિકેશન પરવાનગી',
      'next': 'આગળ',
      'get_started': 'શરૂ કરો',
      'save': 'સાચવો',
      'cancel': 'રદ કરો',
    },
    'Punjabi': {
      'tagline': 'ਤੁਹਾਡਾ ਭਰਾ ਹਮੇਸ਼ਾ ਤੁਹਾਡੇ ਨਾਲ ਹੈ',
      'sos_btn': 'ਮਦਦ',
      'sos_desc': 'ਐਮਰਜੈਂਸੀ ਵਿੱਚ ਦਬਾਓ',
      'safe_status': 'ਤੁਸੀਂ ਸੁਰੱਖਿਅਤ ਹੋ',
      'unsafe_status': 'ਐਮਰਜੈਂਸੀ ਸਰਗਰਮ ਹੈ',
      'volunteer_mode': 'ਵਲੰਟੀਅਰ ਮੋਡ',
      'volunteer_desc': 'ਨੇੜਲੇ ਪੀੜਤਾਂ ਦੀ ਮਦਦ ਲਈ ਉਪਲਬਧ ਰਹੋ',
      'home': 'ਹੋਮ',
      'contacts': 'ਸੰਪਰਕ',
      'helplines': 'ਹੈਲਪਲਾਈਨ',
      'settings': 'ਸੈਟਿੰਗਜ਼',
      'fake_call': 'ਨਕਲੀ ਕਾਲ',
      'travel_mode': 'ਯਾਤਰਾ ਮੋਡ',
      'safe_places': 'ਸੁਰੱਖਿਅਤ ਥਾਵਾਂ',
      'permissions': 'ਮਨਜ਼ੂਰੀਆਂ',
      'permission_desc': 'ਸੁਰੱਖਿਆ ਨੂੰ ਯਕੀਨੀ ਬਣਾਉਣ ਲਈ ਮਨਜ਼ੂਰੀਆਂ ਜ਼ਰੂਰੀ ਹਨ।',
      'location_perm': 'ਲੋਕੇਸ਼ਨ ਮਨਜ਼ੂਰੀ',
      'camera_perm': 'ਕੈਮਰਾ ਮਨਜ਼ੂਰੀ',
      'mic_perm': 'ਮਾਈਕ੍ਰੋਫੋਨ ਮਨਜ਼ੂਰੀ',
      'sms_perm': 'SMS ਮਨਜ਼ੂਰੀ',
      'notification_perm': 'ਨੋਟੀਫਿਕੇਸ਼ਨ ਮਨਜ਼ੂਰੀ',
      'next': 'ਅੱਗੇ',
      'get_started': 'ਸ਼ੁਰੂ ਕਰੋ',
      'save': 'ਸੁਰੱਖਿਅਤ ਕਰੋ',
      'cancel': 'ਰੱਦ ਕਰੋ',
    },
    'Bengali': {
      'tagline': 'আপনার ভাই সর্বদা আপনার সাথে আছে',
      'sos_btn': 'জরুরী',
      'sos_desc': 'জরুরী অবস্থায় চাপুন',
      'safe_status': 'আপনি নিরাপদ আছেন',
      'unsafe_status': 'জরুরী অবস্থা সক্রিয়',
      'volunteer_mode': 'স্বেচ্ছাসেবক মোড',
      'volunteer_desc': 'আশেপাশের ভুক্তভোগীদের সাহায্য করতে প্রস্তুত থাকুন',
      'home': 'হোম',
      'contacts': 'যোগাযোগ',
      'helplines': 'হেল্পলাইন',
      'settings': 'সেটিংস',
      'fake_call': 'ফেক কল',
      'travel_mode': 'ভ্রমণ মোড',
      'safe_places': 'নিরাপদ স্থানসমূহ',
      'permissions': 'অনুমতি সমূহ',
      'permission_desc': 'আপনার নিরাপত্তা নিশ্চিত করতে অনুমতি প্রয়োজন।',
      'location_perm': 'লোকেশন অনুমতি',
      'camera_perm': 'ক্যামেরা অনুমতি',
      'mic_perm': 'মাইক্রোফোন অনুমতি',
      'sms_perm': 'SMS অনুমতি',
      'notification_perm': 'নোটিফিকেশন অনুমতি',
      'next': 'পরবর্তী',
      'get_started': 'শুরু করুন',
      'save': 'সংরক্ষণ',
      'cancel': 'বাতিল',
    },
    'Odia': {
      'tagline': 'ଆପଣଙ୍କ ଭାଇ ସଦାବେଳେ ଆପଣଙ୍କ ସହିତ ଅଛନ୍ତି',
      'sos_btn': 'ସହାୟତା',
      'sos_desc': 'ଆପଦକାଳୀନ ସମୟରେ ଦବାନ୍ତୁ',
      'safe_status': 'ଆପଣ ସୁରକ୍ଷିତ ଅଛନ୍ତି',
      'unsafe_status': 'ଆପଦକାଳୀନ ସକ୍ରିୟ ଅଛି',
      'volunteer_mode': 'ସ୍ଵେଚ୍ଛାସେବୀ ମୋଡ୍',
      'volunteer_desc': 'ଆଖପାଖର ପୀଡିତଙ୍କୁ ସାହାଯ୍ୟ କରିବାକୁ ଉପଲବ୍ଧ ରୁହନ୍ତୁ',
      'home': 'ମୁଖ୍ୟ ପୃଷ୍ଠା',
      'contacts': 'ସମ୍ପର୍କ',
      'helplines': 'ହେଲ୍ପଲାଇନ',
      'settings': 'ସେଟିଙ୍ଗସ',
      'fake_call': 'ନକଲି କଲ୍',
      'travel_mode': 'ଯାତ୍ରା ମୋଡ୍',
      'safe_places': 'ସୁରକ୍ଷିତ ସ୍ଥାନ',
      'permissions': 'ଅନୁମତି',
      'permission_desc': 'ଆପଣଙ୍କ ସୁରକ୍ଷା ପାଇଁ ଅନୁମତି ଆବଶ୍ୟକ।',
      'location_perm': 'ସ୍ଥାନ ଅନୁମତି',
      'camera_perm': 'କ୍ୟାମେରା ଅନುମତି',
      'mic_perm': 'ମାଇକ୍ରୋଫୋନ ଅନುମତି',
      'sms_perm': 'SMS ଅନୁମତି',
      'notification_perm': 'ନୋଟିଫିକେସନ ଅନುମତି',
      'next': 'ପରବର୍ତ୍ତୀ',
      'get_started': 'ଆରମ୍ଭ କରନ୍ତು',
      'save': 'ସଂରକ୍ଷଣ କରନ୍ତು',
      'cancel': 'ବାତିଲ କରନ୍ତು',
    }
  };

  /// Returns localized string value.
  String translate(String key) {
    return _localizedValues[language]?[key] ?? _localizedValues['English']?[key] ?? key;
  }
}
