name: bhai_admin
description: BHAI Web Admin Panel - Response Center Dashboard.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State Management & Routing
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^12.1.3

  # Network & PocketBase API client
  pocketbase: ^0.17.2
  http: ^1.1.2

  # Visualization & Charts
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
